// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: plugin/proto/gcp_server.proto

package golang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Optimization_GCPComputeOptimization_FullMethodName = "/plugingcp.optimization.v1.Optimization/GCPComputeOptimization"
)

// OptimizationClient is the client API for Optimization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizationClient interface {
	GCPComputeOptimization(ctx context.Context, in *GCPComputeOptimizationRequest, opts ...grpc.CallOption) (*GCPComputeOptimizationResponse, error)
}

type optimizationClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizationClient(cc grpc.ClientConnInterface) OptimizationClient {
	return &optimizationClient{cc}
}

func (c *optimizationClient) GCPComputeOptimization(ctx context.Context, in *GCPComputeOptimizationRequest, opts ...grpc.CallOption) (*GCPComputeOptimizationResponse, error) {
	out := new(GCPComputeOptimizationResponse)
	err := c.cc.Invoke(ctx, Optimization_GCPComputeOptimization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizationServer is the server API for Optimization service.
// All implementations must embed UnimplementedOptimizationServer
// for forward compatibility
type OptimizationServer interface {
	GCPComputeOptimization(context.Context, *GCPComputeOptimizationRequest) (*GCPComputeOptimizationResponse, error)
	mustEmbedUnimplementedOptimizationServer()
}

// UnimplementedOptimizationServer must be embedded to have forward compatible implementations.
type UnimplementedOptimizationServer struct {
}

func (UnimplementedOptimizationServer) GCPComputeOptimization(context.Context, *GCPComputeOptimizationRequest) (*GCPComputeOptimizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GCPComputeOptimization not implemented")
}
func (UnimplementedOptimizationServer) mustEmbedUnimplementedOptimizationServer() {}

// UnsafeOptimizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizationServer will
// result in compilation errors.
type UnsafeOptimizationServer interface {
	mustEmbedUnimplementedOptimizationServer()
}

func RegisterOptimizationServer(s grpc.ServiceRegistrar, srv OptimizationServer) {
	s.RegisterService(&Optimization_ServiceDesc, srv)
}

func _Optimization_GCPComputeOptimization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCPComputeOptimizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizationServer).GCPComputeOptimization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Optimization_GCPComputeOptimization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizationServer).GCPComputeOptimization(ctx, req.(*GCPComputeOptimizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Optimization_ServiceDesc is the grpc.ServiceDesc for Optimization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Optimization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugingcp.optimization.v1.Optimization",
	HandlerType: (*OptimizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GCPComputeOptimization",
			Handler:    _Optimization_GCPComputeOptimization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/gcp_server.proto",
}
