name: Pre-Release

on:
    workflow_dispatch:

env:
    REPOSITORY_OWNER: "kaytu-io"
    REPOSITORY_NAME: "plugin-gcp"

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
      previous_tag: ${{ steps.set_latest_tag.outputs.previous_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: none
          pre_release_branches: main
          append_to_pre_release_tag: rc
          tag_prefix: v
      - name: Set latest tag output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          fi
          echo "previous_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
  release:
    runs-on: ubuntu-latest
    needs:
      - tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ needs.tag.outputs.latest_tag }}
          GORELEASER_PREVIOUS_TAG: ${{ needs.tag.outputs.previous_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          REPOSITORY_OWNER: ${{ env.REPOSITORY_OWNER }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          GORELEASER_MAKE_LATEST: "false"